apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle

  nfs:
    server: 10.238.130.31
    path: /data/nfsshare
