apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-camel-cluster-singleton-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi