kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spring-camel-cluster-singleton
subjects:
- kind: ServiceAccount
  name: spring-camel-cluster-singleton
roleRef:
  kind: Role
  name: spring-camel-cluster-singleton
  apiGroup: rbac.authorization.k8s.io
