kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spring-camel-cluster-singleton
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
